# Generated by Django 3.1.4 on 2020-12-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_auto_20201218_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFile',
        ),
    ]
